In [12]:
import komm

In [13]:
code1 = komm.ConvolutionalCode(
    feedforward_polynomials=[
        [0b11, 0b10, 0b11],
        [0b10, 0b01, 0b01],
    ],
)

(n, k, mu) = (code1.num_output_bits, code1.num_input_bits, code1.memory_order)

display((n, k, mu))

encoder1 = komm.ConvolutionalStreamEncoder(code1)

display(encoder1([0, 1, 1, 1, 1, 0]))
display(encoder1([0, 1, 1, 1, 1, 0]))

(3, 2, np.int64(1))

array([0, 1, 1, 0, 1, 0, 1, 1, 0])

array([1, 0, 0, 0, 1, 0, 1, 1, 0])

In [14]:
code2 = komm.ConvolutionalCode(
    feedforward_polynomials=[
        [0b111, 0b101],
    ],
)

(n, k, mu) = (code2.num_output_bits, code2.num_input_bits, code2.memory_order)

display((n, k, mu))

encoder2 = komm.ConvolutionalStreamEncoder(code2)

display(encoder2([1, 0, 1, 1, 0]))
display(encoder2([1, 0, 1, 1, 0]))

(2, 1, np.int64(2))

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1])

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1])