In [21]:
import komm
import numpy as np

In [15]:
code1 = komm.ConvolutionalCode(
    feedforward_polynomials=[
        [0b11, 0b10, 0b11],
        [0b10, 0b01, 0b01],
    ],
)

(n, k, mu) = (code1.num_output_bits, code1.num_input_bits, code1.memory_order)

display((n, k, mu))

encoder1 = komm.ConvolutionalStreamEncoder(code1)

display(encoder1([0, 1, 1, 1, 1, 0]))
display(encoder1([0, 1, 1, 1, 1, 0]))

(3, 2, np.int64(1))

array([0, 1, 1, 0, 1, 0, 1, 1, 0])

array([1, 0, 0, 0, 1, 0, 1, 1, 0])

In [16]:
code2 = komm.ConvolutionalCode(
    feedforward_polynomials=[
        [0b111, 0b101],
    ],
)

(n, k, mu) = (code2.num_output_bits, code2.num_input_bits, code2.memory_order)

display((n, k, mu))

encoder2 = komm.ConvolutionalStreamEncoder(code2)

display(encoder2([1, 0, 1, 1, 0]))
display(encoder2([1, 0, 1, 1, 0]))

(2, 1, np.int64(2))

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1])

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [17]:
block_code_trunc = komm.TerminatedConvolutionalCode(
    code2, num_blocks=5, mode="direct-truncation"
)

(n, k, mu) = (
    block_code_trunc.length,
    block_code_trunc.dimension,
    block_code_trunc.minimum_distance,
)

display((n, k, mu))

block_code_trunc.enc_mapping([1, 0, 1, 1, 0])

(10, 5, np.int64(2))

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1])

In [18]:
block_code_zero = komm.TerminatedConvolutionalCode(
    code2, num_blocks=5, mode="zero-termination"
)

(n, k, mu) = (
    block_code_zero.length,
    block_code_zero.dimension,
    block_code_zero.minimum_distance,
)

display((n, k, mu))

block_code_zero.enc_mapping([1, 0, 1, 1, 0])

(np.int64(14), 5, np.int64(5))

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0])

In [19]:
block_code_tail = komm.TerminatedConvolutionalCode(
    code2, num_blocks=5, mode="tail-biting"
)

(n, k, mu) = (
    block_code_tail.length,
    block_code_tail.dimension,
    block_code_tail.minimum_distance,
)

display((n, k, mu))

block_code_tail.enc_mapping([1, 0, 1, 1, 0])

(10, 5, np.int64(3))

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [121]:
h = 100
block_code = komm.TerminatedConvolutionalCode(
    code2, num_blocks=h, mode="zero-termination"
)
encoder = komm.BlockEncoder(block_code)
# TODO: SUBIR COMMIT NO KOMM PARA TROCAR UNDERLINE POR HÍFEN
decoder = komm.BlockDecoder(block_code, method="viterbi_hard")

u = np.random.randint(0, 2, h)
v = encoder(u)

channel = komm.BinarySymmetricChannel(0.05)
b = channel(v)

u_hat = decoder(b)
errors = np.sum(v != b)

ber = np.mean(u != u_hat)

print(ber)

0.0
